### PR TITLE
update to works with newer osx versions

### PR DESCRIPTION
**Pull request by matteofilippetto**
update to works with newer osx versions
- replace airport command with wdutil
- call sudo to execute locationchanger

### CODE REVIEW

**Review by putchi — CHANGES_REQUESTED** [review]
wdutil info | awk -F ' SSID.*: ' '/ SSID / {print $2}'

is more concise and sufficiently robust for typical output formats. It leverages awk's pattern matching to both identify lines of interest and split them based on a flexible pattern, which might make it more adaptable to slight variations in output format.

Please change it to make it like that.

**Review by putchi — CHANGES_REQUESTED** [review]
wdutil info | awk -F ' SSID.*: ' '/ SSID / {print $2}'

is more concise and sufficiently robust for typical output formats. It leverages awk's pattern matching to both identify lines of interest and split them based on a flexible pattern, which might make it more adaptable to slight variations in output format.

Please change it to make it like that. 

As well as the `wdutil info | awk -F ' SSID.*: ' '/ SSID / {print $2}'` will not return any output without the use of sudo like so: `sudo wdutil info | awk -F ' SSID.*: ' '/ SSID / {print $2}'`

**Comment by putchi** [comment]
example:
Screenshot 2024-03-12 at 23 19 37

**Comment by matteofilippetto** [comment]
ok modified AWK command as suggested 

regarding sudo , is not enough the change to LocationChanger.plist ?  because I'm using it like this without problem

**Comment by kshcherban** [comment]
> wdutil info | awk -F ' SSID.*: ' '/ SSID / {print $2}'
> 
> is more concise and sufficiently robust for typical output formats. It leverages awk's pattern matching to both identify lines of interest and split them based on a flexible pattern, which might make it more adaptable to slight variations in output format.
> 
> Please change it to make it like that.
> 
> As well as the `wdutil info | awk -F ' SSID.*: ' '/ SSID / {print $2}'` will not return any output without the use of sudo like so: `sudo wdutil info | awk -F ' SSID.*: ' '/ SSID / {print $2}'`

Alternatively you can use this sed (BSD) command:
```
sudo /usr/bin/wdutil info | sed -n 's/^[[:space:]]*SSID[[:space:]]*:[[:space:]]*//p'
```

It will trim everything except WiFi name.

**Pull request closed without merging**
